version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Ho_Chi_Minh"
    open-pull-requests-limit: 5
    versioning-strategy: increase
    labels:
      - "dependencies"
    assignees:
      - "hungfnguyen"
