"""rva-core — Shared models, settings, and utilities."""

from core.constants import (
    DEFAULT_ALERT_COOLDOWN_SEC,
    DEFAULT_ALERT_DENSITY_THRESHOLD,
    DEFAULT_CLASS_FILTER,
    DEFAULT_CLIP_JPEG_QUALITY,
    DEFAULT_CONF_THRES,
    DEFAULT_FPS_TARGET,
    DEFAULT_FRAME_QUEUE_SIZE,
    DEFAULT_FRAME_SAMPLE_INTERVAL_SEC,
    DEFAULT_GRACEFUL_SHUTDOWN_SEC,
    DEFAULT_HEALTH_CHECK_INTERVAL_SEC,
    DEFAULT_JPEG_QUALITY,
    DEFAULT_POST_BUFFER_SEC,
    DEFAULT_PRE_BUFFER_SEC,
    DEFAULT_RECONNECT_DELAY_MAX_SEC,
    SCHEMA_VERSION,
    TOPIC_ALERTS,
    TOPIC_DETECTION_FRAMES,
    TOPIC_DLQ,
    TOPIC_MEDIA_EVENTS,
    TOPIC_SYSTEM_METRICS,
    TOPIC_TRACK_LIFECYCLE,
)
from core.models import (
    AlertEvent,
    BBox,
    BBoxNorm,
    Centroid,
    CentroidNorm,
    ClipCreatedResult,
    DetectionFrameEvent,
    DetectionObject,
    ImageSize,
    Runtime,
    SampledFrameResult,
    Source,
    TrackLifecycleEvent,
)
from core.settings import (
    get_bool,
    get_class_filter,
    get_float,
    get_int,
    get_optional,
    get_str,
    load_yaml_config,
)
from core.time_utils import ensure_utc, now_iso, now_utc

__all__ = [
    # Models
    "AlertEvent",
    "BBox",
    "BBoxNorm",
    "Centroid",
    "CentroidNorm",
    "ClipCreatedResult",
    "DetectionFrameEvent",
    "DetectionObject",
    "ImageSize",
    "Runtime",
    "SampledFrameResult",
    "Source",
    "TrackLifecycleEvent",
    # Settings
    "get_bool",
    "get_class_filter",
    "get_float",
    "get_int",
    "get_optional",
    "get_str",
    "load_yaml_config",
    # Time utils
    "ensure_utc",
    "now_iso",
    "now_utc",
    # Constants
    "DEFAULT_ALERT_COOLDOWN_SEC",
    "DEFAULT_ALERT_DENSITY_THRESHOLD",
    "DEFAULT_CLASS_FILTER",
    "DEFAULT_CLIP_JPEG_QUALITY",
    "DEFAULT_CONF_THRES",
    "DEFAULT_FPS_TARGET",
    "DEFAULT_FRAME_QUEUE_SIZE",
    "DEFAULT_FRAME_SAMPLE_INTERVAL_SEC",
    "DEFAULT_GRACEFUL_SHUTDOWN_SEC",
    "DEFAULT_HEALTH_CHECK_INTERVAL_SEC",
    "DEFAULT_JPEG_QUALITY",
    "DEFAULT_POST_BUFFER_SEC",
    "DEFAULT_PRE_BUFFER_SEC",
    "DEFAULT_RECONNECT_DELAY_MAX_SEC",
    "SCHEMA_VERSION",
    "TOPIC_ALERTS",
    "TOPIC_DETECTION_FRAMES",
    "TOPIC_DLQ",
    "TOPIC_MEDIA_EVENTS",
    "TOPIC_SYSTEM_METRICS",
    "TOPIC_TRACK_LIFECYCLE",
]
