"""Conversion helpers between Supervision detections, track dicts, and events."""

from __future__ import annotations

from typing import Any

import numpy as np


def detections_to_track_objects(detections: Any, names: dict[int, str] | None = None) -> list[dict[str, Any]]:
    """Convert ``sv.Detections`` into the local track dict shape.

    The existing worker and visualizer already understand this shape, so it is
    the compatibility bridge between the new Supervision pipeline and the v1
    event path.
    """

    names = names or {}
    xyxy = np.asarray(getattr(detections, "xyxy", []), dtype=float)
    if xyxy.size == 0:
        return []

    confidence = getattr(detections, "confidence", None)
    class_id = getattr(detections, "class_id", None)
    tracker_id = getattr(detections, "tracker_id", None)

    objects: list[dict[str, Any]] = []
    for idx, box in enumerate(xyxy):
        cls = _array_value(class_id, idx, 0, int)
        raw_track_id = _array_value(tracker_id, idx, -1, int)
        conf = _array_value(confidence, idx, 0.0, float)
        label = names.get(cls, "person" if cls == 0 else str(cls))
        objects.append(
            {
                "id": raw_track_id,
                "raw_track_id": None if raw_track_id < 0 else raw_track_id,
                "bbox": [float(v) for v in box.tolist()],
                "cls": cls,
                "label": label,
                "conf": conf,
                "track_state": "matched",
                "measurement_source": "full_body",
                "missed_frames": 0,
                "is_predicted": False,
            }
        )
    return objects


def add_global_track_ids(tracks: list[dict[str, Any]], camera_id: str) -> None:
    for track in tracks:
        canonical_id = _safe_int(track.get("id"))
        if canonical_id is None or canonical_id < 0:
            continue
        track.setdefault("global_track_id", f"{camera_id}_g_{canonical_id:06d}")
        if track.get("raw_track_id") is None:
            raw_ids = track.get("detector_ids")
            if isinstance(raw_ids, list) and raw_ids:
                track["raw_track_id"] = int(raw_ids[-1])
            else:
                track["raw_track_id"] = canonical_id


def track_to_detection(
    *,
    frame_index: int,
    object_index: int,
    obj: dict[str, Any],
    width: int,
    height: int,
    zones: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    x1, y1, x2, y2 = map(float, obj["bbox"])
    w_box = max(0.0, x2 - x1)
    h_box = max(0.0, y2 - y1)
    cx = x1 + w_box / 2.0
    cy = y1 + h_box / 2.0
    anchor_x = cx
    anchor_y = y2
    zones = zones or []
    primary_zone = next((zone for zone in zones if zone.get("is_primary")), None)
    in_queue = bool(primary_zone and primary_zone.get("zone_type") == "queue")

    detection = {
        "det_id": f"{frame_index}-{object_index}",
        "class": obj.get("label", "person"),
        "class_id": int(obj.get("cls", 0)),
        "conf": float(obj.get("conf", 0.0)),
        "bbox": {"x1": x1, "y1": y1, "x2": x2, "y2": y2},
        "bbox_norm": {
            "x": _safe_div(x1, width),
            "y": _safe_div(y1, height),
            "w": _safe_div(w_box, width),
            "h": _safe_div(h_box, height),
        },
        "centroid": {"x": int(cx), "y": int(cy)},
        "centroid_norm": {"x": _safe_div(cx, width), "y": _safe_div(cy, height)},
        # v1 compatibility: this remains the application-stabilized integer ID
        # generated by TrackMemory. raw_track_id carries the tracker-native ID.
        "track_id": None if _safe_int(obj.get("id")) is None or int(obj.get("id")) < 0 else int(obj["id"]),
        "raw_track_id": obj.get("raw_track_id"),
        "global_track_id": obj.get("global_track_id"),
        "track_state": str(obj.get("track_state", "matched")),
        "measurement_source": str(obj.get("measurement_source", "full_body")),
        "missed_frames": int(obj.get("missed_frames", 0)),
        "is_predicted": bool(obj.get("is_predicted", False)),
        "anchor": {
            "type": "bottom_center",
            "x": int(anchor_x),
            "y": int(anchor_y),
            "x_norm": _safe_div(anchor_x, width),
            "y_norm": _safe_div(anchor_y, height),
        },
        "zones": zones,
        "queue": {
            "in_queue": in_queue,
            "queue_zone_id": primary_zone.get("zone_id") if in_queue and primary_zone else None,
            "wait_ms": int(obj.get("queue_wait_ms", 0)) if in_queue else 0,
            "wait_seconds": int(obj.get("queue_wait_seconds", 0)) if in_queue else 0,
        },
        "quality": {
            "bbox_area": w_box * h_box,
            "is_near_frame_edge": x1 <= 2 or y1 <= 2 or x2 >= width - 2 or y2 >= height - 2,
            "is_low_confidence": float(obj.get("conf", 0.0)) < 0.25,
            "is_zone_boundary_near": False,
        },
    }
    return detection


def bottom_center(obj: dict[str, Any]) -> tuple[float, float]:
    x1, _y1, x2, y2 = map(float, obj["bbox"])
    return ((x1 + x2) / 2.0, y2)


def _array_value(values: Any, idx: int, default: Any, caster: Any) -> Any:
    if values is None:
        return default
    try:
        if idx >= len(values):
            return default
        return caster(values[idx])
    except Exception:
        return default


def _safe_int(value: Any) -> int | None:
    try:
        return int(value)
    except (TypeError, ValueError):
        return None


def _safe_div(value: float, denominator: int) -> float:
    return float(value) / float(denominator) if denominator else 0.0
